apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
    limits:
      storage: 100Mi
status: {}
