{{- if .Values.openapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openapi
  labels:
    {{- include "app.labelsOpenapi" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.openapi.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabelsOpenapi" . | nindent 4 }}
{{- end }}
