{{- if .Values.openapi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-openapi
  labels:
    {{- include "app.labelsOpenapi" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabelsOpenapi" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabelsOpenapi" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-openapi
          image: {{ .Values.openapi.image }}:{{ .Values.openapi.tag }}
          imagePullPolicy: {{ .Values.openapi.pullPolicy }}
          env:
            - name: SERVERS
              value: "http://weaver-cluster.com/"
            - name: URLS
              value: >-
                [
                { name: "v1", url: "http://weaver-cluster.com/{{.Release.Name}}/api/schema/?version=v1"},
                { name: "v2", url: "http://weaver-cluster.com/{{.Release.Name}}/api/schema/?version=v2" }
                ]
            - name: FILTER
              value: "true"
            - name: LAYOUT
              value: "StandaloneLayout"
            - name: DEFAULT_MODELS_EXPAND_DEPTH
              value: "-1"
          ports:
            - name: http
              containerPort: {{ .Values.openapi.port }}
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}