{{- if .Values.openapi.enabled }}
{{- if eq "traefik" .Values.ingress.className }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-openapi-strip-prefix
spec:
  stripPrefix:
    forceSlash: true
    prefixes:
      - /{{ .Release.Name }}/openapi/
{{- end}}
{{- end}}